### ISSUE TITLE
open the work done using NetworkGT tools in Google earth

### ISSUE THREAD

**Issue by xxostars** [BjornNyberg/NetworkGT#32] opened 2023-05-05 17:10 UTC
Hi again
I want to Know how to open my work in qgis file with google earth same like this example, i tried but it looks different when it turned to google earth
<img width="959" alt="Screenshot 2023-05-05 010847" src="https://user-images.githubusercontent.com/127874728/236522525-365f3d89-32ab-4ec4-b4bd-c893fb881ec3.png">

**Comment by BjornNyberg** [comment] 2023-05-07 14:16
Considering this is not a bug/error with the NetworkGT plugin, I will close this issue. Have a look at this [video](https://www.youtube.com/watch?v=pfQQONQQ5TM) as an example, but there are many different available solutions.

**Closed as completed by BjornNyberg** 2023-05-07 14:16 UTC
