### ISSUE TITLE
How to map the fracture polylines?

### ISSUE THREAD

**Issue by xxostars** [BjornNyberg/NetworkGT#26] opened 2023-03-18 11:50 UTC
I would lilke to know how you created the two files in the usre guide? I am working in a project and I must ues the NetworkGT toolbar in QGIS, and I am usnig a DEM image from earth explorer.
<img width="962" alt="Screenshot 2023-03-18 154859" src="https://user-images.githubusercontent.com/127874728/226103799-41db608e-aa22-4181-85a4-d0190b34e806.png">

Please help me as soon as possible, I am looking forward for your answer.

**Comment by BjornNyberg** [comment] 2023-03-29 18:53
Hi @xxostars 

To create the fracture network and interpretation bounds you will need to digitize those manually. An example of how to use the digitzation tools can be found [here](https://www.youtube.com/watch?v=Zer558SnKX4). Other more advanced automated options do [exist](https://github.com/BjornNyberg/NetworkGT/wiki/1.-Digitising-Tools#automated-fracture-digitisation) but I suggest starting with the manual approach first. 

Considering this is not a bug with the actual toolkit, I will close this issue for now.

**Closed as completed by BjornNyberg** 2023-03-29 18:53 UTC
