### ISSUE TITLE
Digitise fracture Network

### ISSUE THREAD

**Issue by xxostars** [BjornNyberg/NetworkGT#31] opened 2023-05-02 13:18 UTC
Hi 
I am facing a problem in the digitising fracture network from an Image after using thresholding tool. 
The image in the format of (JPG File), and I tried to do it when it is in grayscale and RGB colored image and it didn't work.  
could you please help me. 
<img width="952" alt="Screenshot 2023-05-02 165220" src="https://user-images.githubusercontent.com/127874728/235677853-987f0e5c-6104-4a6b-9373-9a6d68b1e443.png">

**Comment by BjornNyberg** [comment] 2023-05-02 15:51
Hi again @xxostars 

Based on the error messages it would appear that your image is not georeferenced considering that -434 is not a valid latitude. Check out the QGIS georeferencing guidelines [here](https://docs.qgis.org/3.28/en/docs/training_manual/forestry/map_georeferencing.html?highlight=georeference%20map). Also note that it is important that your image is in the correct projection, a good explanation of projections is available on this youtube [video](https://www.youtube.com/watch?v=jVn1uCuhO_4). 

Cheers,
Bjorn

**Comment by xxostars** [comment] 2023-05-02 18:00
Thanks it woeked! But I faced another problem while using Branches an Nodes tool. 
<img width="786" alt="Screenshot 2023-05-02 215507" src="https://user-images.githubusercontent.com/127874728/235747398-6b4ccd00-7e04-4ae8-b1d1-0f30b802dc49.png">

**Comment by BjornNyberg** [comment] 2023-05-02 18:27
Hi @xxostars 

As the tool suggests, you need to fix the geometries (repair tool, fix geometries tool) or choose to ignore them in the options of the processing toolbox.

Bjorn

**Comment by xxostars** [comment] 2023-05-02 18:45
I didn't get it :(
Please explain it more, I'm working on research, so excuse me if I bother you with my questions

With kind regards,

Rayan Al Mamari
17-0232

________________________________

**Comment by BjornNyberg** [comment] 2023-05-02 19:06
Hi again,

Use the repair tool or go to your processing toolbox options and select
"skip (ignore features) with invalid geometries".

![image](https://user-images.githubusercontent.com/37108459/235762093-1e51eb1e-4bfc-4cc0-a5f0-a0012a8b8f05.png)

![image](https://user-images.githubusercontent.com/37108459/235762224-e8014795-19fa-4605-9b45-260781176357.png)

**Comment by xxostars** [comment] 2023-05-04 21:15
Hi again 
I want to Know how to open my work in qgis file with google earth same like this example, i tried but it looks different when it turned to google earth
<img width="959" alt="Screenshot 2023-05-05 010847" src="https://user-images.githubusercontent.com/127874728/236331626-e81d70e3-76bd-469e-acfe-fbdffff8767d.png">

**Comment by BjornNyberg** [comment] 2023-05-07 14:13
Considering this is not a bug/error with the NetworkGT plugin, I will close this issue.

**Closed as completed by BjornNyberg** 2023-05-07 14:13 UTC
